#' Separate a PaleoBuddy simulation into monophyletic clades
#'
#' \code{findClades} find an separate monophyletic clades from the
#' \code{BDSim} function. Note that the function is uneffective 
#' in simulations with just a single starting species.
#'
#' @param sim a simulation from the \code{BDSim} function. The 
#' function accept simulations with any number of starting species.
#'
#' @author written by Bruno Petrucci and Matheus Januario
#'
#' @return A \code{list} object with (named) monophyletic clades 
#' generated by a PaleoBuddy simulation.
#'
#' @examples
#' 
#' # first, let us try a simulation with 3 clades,
#' sim<-BDSim(N0 = 3, pp = .1, qq = 0.1, tmax = 10)
#' 
#' # in case first simulation has a small number of lineages
#' while(length(sim$TE)<20){
#'   sim<-BDSim(N0 = 3, pp = .1, qq = 0.1, tmax = 10)
#' }
#' 
#' # using the functions
#' test <- findClades(sim)
#' 
#' # testing if it works:
#' par(mfrow=c(1,length(test)))
#' for(i in 1:length(test)){
#'   if(sum(test[[i]]$PAR %in% i)<1){
#'     plot(NA, xlim = c(-1,1), ylim=c(-1,1))
#'     text("simulation with \n just one lineage", x = 0, y=.5, cex=2)
#'   }else{
#'     if(requireNamespace("ape", quietly = TRUE)) {
#'       p=ape::plot.phylo(MakePhylo(test[[i]]), 
#'                         main="red = extinction events \n blue = speciation events");
#'       ape::axisPhylo()
#'     }
#' 
#'     # checking speciation times:
#'     for(j in 2:length(test[[i]]$TS)){
#'       # the subtraction is just to adjust the wt with the plot scale
#'       lines(x=c( 
#'         sort(test[[i]]$TS, decreasing = T)[2]-test[[i]]$TS[j],
#'         sort(test[[i]]$TS, decreasing = T)[2]-test[[i]]$TS[j]),
#'         y=c(p$y.lim[1],p$y.lim[2]),lwd=2, col="blue")
#'     }
#' 
#'     # checking extinction times:
#'     for(j in 1:length(sim$TE)){
#'       # the subtraction is just to adjust the wt with the plot scale
#'       lines(x=c( 
#'         sort(test[[i]]$TS, decreasing = T)[2]-test[[i]]$TE[j],
#'         sort(test[[i]]$TS, decreasing = T)[2]-test[[i]]$TE[j]),
#'         y=c(p$y.lim[1],p$y.lim[2]),lwd=2, col="red")
#'     }
#'   }
#' }
#' 
#' # it works with any number of clades, of course
#' sim<-BDSim(N0 = 5, pp = .1, qq = 0.1, tmax = 10)
#' 
#' # in case first simulation has a small number of lineages
#' while(length(sim$TE)<20){
#'   sim<-BDSim(N0 = 5, pp = .1, qq = 0.1, tmax = 10)
#' }
#' 
#' # using the functions
#' test <- findClades(sim)
#' 
#' # testing if it works:
#' par(mfrow=c(1,length(test)))
#' for(i in 1:length(test)){
#'   if(sum(test[[i]]$PAR %in% i)<1){
#'     plot(NA, xlim = c(-1,1), ylim=c(-1,1))
#'     text("simulation with \n just one lineage", x = 0, y=.5, cex=2)
#'   }else{
#'     if(requireNamespace("ape", quietly = TRUE)) {
#'       p=ape::plot.phylo(MakePhylo(test[[i]]), 
#'                         main="red = extinction events \n blue = speciation events");
#'       ape::axisPhylo()
#'     }
#'     
#'     # checking speciation times:
#'     for(j in 2:length(test[[i]]$TS)){
#'       # the subtraction is just to adjust the wt with the plot scale
#'       lines(x=c( 
#'         sort(test[[i]]$TS, decreasing = T)[2]-test[[i]]$TS[j],
#'         sort(test[[i]]$TS, decreasing = T)[2]-test[[i]]$TS[j]),
#'         y=c(p$y.lim[1],p$y.lim[2]),lwd=2, col="blue")
#'     }
#'     
#'     # checking extinction times:
#'     for(j in 1:length(sim$TE)){
#'       # the subtraction is just to adjust the wt with the plot scale
#'       lines(x=c( 
#'         sort(test[[i]]$TS, decreasing = T)[2]-test[[i]]$TE[j],
#'         sort(test[[i]]$TS, decreasing = T)[2]-test[[i]]$TE[j]),
#'         y=c(p$y.lim[1],p$y.lim[2]),lwd=2, col="red")
#'     }
#'   }
#' }
#' 
#' # including one clade, of course
#' sim<-BDSim(N0 = 1, pp = .2, qq = 0.1, tmax = 10)
#' while(length(sim$TE)<10){
#'  sim<-BDSim(N0 = 1, pp = .1, qq = 0.1, tmax = 10)
#' }
#' 
#' 
#' par(mfrow=c(1,2))
#' if (requireNamespace("ape", quietly = TRUE)) {
#'  ape::plot.phylo(MakePhylo(sim), main="original");ape::axisPhylo()
#'  ape::plot.phylo(MakePhylo(findClades(sim)[[1]]), main="after findClades()");ape::axisPhylo()     #those should be equal
#' }
#' @name findClades
#' @rdname findClades
#' @export

findClades <- function(sim) {
  # make a list of species
  sp <- 1:length(sim$TE)
  
  # create a list to hold all the info
  res <- c()
  
  while (length(sp) > 0) {
    # lineage starts with a species
    lin <- c(sp[1])
    
    # daughters of the first species of the lineage
    dau <- which(sim$PAR == sp[1])
    
    # while species in the lineage have daughters
    while (length(dau) > 0) {
      # append the daughters to the lineage
      lin <- c(lin, dau)
      
      # find the daughters of the previous daughters
      dau <- which(sim$PAR %in% dau)
    }
    
    # make vectors for the clade
    TE <- sim$TE[lin]
    TS <- sim$TS[lin]
    PAR <- sim$PAR[lin]
    EXTANT <- sim$EXTANT[lin]
    
    # PAR here still follows the identifications on the original sim, so we need
    # to rename the species
    if(length(PAR)>1){
      # first species of the clade (the one that generated the second) is 1
      PAR[PAR==PAR[2]] = 1 
      
      # every other species follows the order in lin, to preserve the order
      # of TE and TS
      for (i in 2:length(PAR)) {
        if (!is.na(PAR[i-1]) & PAR[i] > PAR[i-1]) {
          PAR[PAR==PAR[i]] = which(lin==PAR[i])
        }
      }  
    }
    
    # append it to a sim
    sim1 <- list(TE=TE, TS=TS, PAR=PAR,
                 EXTANT=EXTANT)
    
    # append the sim to the result
    res <- c(res, sim1)
    
    # delete this clade from the list
    sp <- sp[!sp %in% lin]
  }
  
  # append to final list:
  ids<-seq(1, length(res), by=4)
  final<-list()
  
  for(i in 1:length(ids)){
    seqs<-seq(from=ids[i], to=ids[i]+3, by=1)
    final[[paste0("clade_",i)]]=res[seqs]
  }
  
  return(final)
}
